name = "example"

[language]
name = "python"
version = "3.13"

[framework]
name = "django"
version = "5.2"

[environment]
manager = "venv"

[commands]
run = "python manage.py runserver"
test = "python manage.py test"
